### ISSUE TITLE
Use a free and open source map displaying solution instead of proprietary Mapbox

### ISSUE THREAD

**Issue by TheSunCat** [savvasdalkitsis/uhuruphotos-android#137]
Currently it is impossible to build UhuruPhotos without providing my credit card information to Mapbox and by extent Stripe Inc. Because of this, it is impossible for me to contribute to UhuruPhotos development.
An alternative to Mapbox that seems promising is [MapLibre](https://github.com/maplibre/maplibre-gl-native), which is a fork of Mapbox from before it became proprietary and thus should be nearly a drop-in replacement.

**Comment by savvasdalkitsis** [comment]
I will look at making the mapbox portion of the app an optional module so that the default build doesn't require it as a first step. integrating another mapping provider can be done but is not high in my list atm (next big feature will be backup/sync which will get us closer to a public release)

As you've noted in the gitter chat, I am now providing APK and AAB binaries in the releases pages so this should unblock people that cannot join the private beta on play store.

I will keep this issue open though for a future third map provider integration

**Comment by savvasdalkitsis** [comment]
This is now implemented. Duplicated in https://github.com/savvasdalkitsis/uhuruphotos-android/issues/277 as forgot this issue was already raised

**Comment by savvasdalkitsis** [comment]
The work to create separate build variants to exclude mapbox from the build pipeline hasn't happened yet but will be done as part of https://github.com/savvasdalkitsis/uhuruphotos-android/issues/135
